### ISSUE TITLE
Using function component to add logic method for calculator

### ISSUE THREAD

**Issue by hienphan0111** [hienphan0111/Math-magicians#6]
In this section, I have used function component to implement adding logic method for calculator, In more detail is following:
- Compose a Calculator function:
https://github.com/hienphan0111/Math-magicians/blob/c75e47c066a9904db6087ff1cba01f6d82ea43f9/src/components/Calculator.jsx#L5
- Declare an array that contains the definition of calculator's key. In which, each key will be an object with id and name attributes.
https://github.com/hienphan0111/Math-magicians/blob/c75e47c066a9904db6087ff1cba01f6d82ea43f9/src/components/Calculator.jsx#L6
- Use `useState` Hook to manage state of Calculator component.
https://github.com/hienphan0111/Math-magicians/blob/c75e47c066a9904db6087ff1cba01f6d82ea43f9/src/components/Calculator.jsx#L91
- Compose a calHandler function to handler click calculator key events and set state of Calculator depend on what key was pressed. Inside this function, I have used a calculator module that is located in the logic folder to do calculator logic.
https://github.com/hienphan0111/Math-magicians/blob/c75e47c066a9904db6087ff1cba01f6d82ea43f9/src/components/Calculator.jsx#L93-L96
- Compose a display function to control what would be on the screen of calculator. 
https://github.com/hienphan0111/Math-magicians/blob/c75e47c066a9904db6087ff1cba01f6d82ea43f9/src/components/Calculator.jsx#L98
- Finally, The Calculator component will return what will render when we invoke this component.

**Comment by Davidosky007** [comment]
Hi @hienphan0111 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* Well-explained use of functional components
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
